# Generated by Django 4.2.23 on 2026-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_extra_fields", "0002_customextrafields_birthdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customextrafields",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="customextrafields",
            name="favorite_language",
        ),
        migrations.RemoveField(
            model_name="customextrafields",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="customextrafields",
            name="nickname",
        ),
        migrations.AddField(
            model_name="customextrafields",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("undergraduate_student", "Étudiant-e au premier cycle"),
                    ("masters_student", "Étudiant-e à la maîtrise"),
                    ("doctoral_student", "Étudiant-e au doctorat"),
                    ("postdoctoral_fellow", "Stagiaire post-doctoral"),
                    ("professor", "Professeur-e"),
                    ("research_professional", "Professionnel-le de recherche"),
                    ("other", "Autre"),
                ],
                max_length=50,
                verbose_name="Position",
            ),
        ),
        migrations.AddField(
            model_name="customextrafields",
            name="research_area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("natural_sciences", "Sciences naturelles"),
                    ("engineering_and_technology", "Génie et technologies"),
                    ("medical_health_and_life_sciences", "Sciences médicales, de la santé et de la vie"),
                    ("agricultural_and_veterinary_sciences", "Sciences agricoles et vétérinaires"),
                    ("social_sciences", "Sciences sociales"),
                    ("humanities_and_the_arts", "Sciences humaines et arts"),
                ],
                max_length=50,
                verbose_name="Research area",
            ),
        ),
    ]
